ヘッダーとヒーローの作成
IwaseMio/frontend-basic-site pull request #1
Opened 2023-07-09 15:48 UTC by IwaseMio

若干ヘッダー文字の位置と画像の縦幅がずれるのがよくわかりませんでした🙇‍♀️

2023-07-11 16:51 UTC, higashiji2000 requested changes
見た目に関しては全く問題ないです！！
細かい点ですが確認お願いします。

> 若干ヘッダー文字の位置と画像の縦幅がずれるのがよくわかりませんでした🙇‍♀️

こちらの指す内容があまり理解できませんでした 🙇 
自分の認識では問題なさそうなのですが、気になる点があればスクリーンショット等を貼っていただけると助かります 🙌

2023-07-11 16:51 UTC, higashiji2000 commented on img/arrow-right.png
このようなアイコン素材に関しては、基本的に svg を使用します。
pngの方は削除してしまってください。

2023-07-11 16:51 UTC, higashiji2000 commented on img/logo.png
ロゴも同様に svg を使用するので、png は削除お願いします！

2023-07-11 16:51 UTC, higashiji2000 commented on index.html
> +        <img src="./img/logo.svg" alt="ロゴ" class="header-logo" />
```suggestion
        <img src="./img/logo.svg" alt="Grand Players" class="header-logo" />
```
`alt` 属性は、目の見えない人がスクリーンリーダーを使ってWEBサイトを閲覧する際に読み上げられる文言であったり、何らかの不具合で画像が表示できなかった場合の代替テキストを定義します。
今回のロゴのように、画像が表現している内容が文字の場合は、その文字を`alt`属性に入れるのが適切です。

[教材のimgに関する部分](https://www.notion.so/shinonome-inc/img-4cb5ecb9ce9d492396e4249afbf63183?pvs=4)でもaltについて軽く触れているので、参考にしてみてください。

2023-07-12 00:58 UTC, IwaseMio commented
@higashiji2000 
ありがとうございます！
見た目に関しては、750px以下のときロゴの位置が若干お手本とずれてしまうのが気になりました。
![image](https://github.com/IwaseMio/frontend-basic-site/assets/132257044/19b19a9b-b37c-4587-a9e3-99ea439d01b8)

2023-07-12 01:59 UTC, IwaseMio commented
png削除修正しました！

2023-07-12 04:51 UTC, higashiji2000 reviewed
### ロゴが上に寄る問題について

<img width="1512" alt="image" src="https://github.com/IwaseMio/frontend-basic-site/assets/83479175/5775e335-26fb-40d6-a359-dbe2e294a33e">

`h1` に設定された `height` の値が画像の高さより大きいため、画像が上の方に寄ってしまっています。

<img width="1512" alt="image" src="https://github.com/IwaseMio/frontend-basic-site/assets/83479175/086e56af-6d30-4837-9b9a-7f4ed0482ce8">

`height` の指定を削除すると、`h1` の高さが中身によって決定されるようになります。（figmaでいうhug）
`header` に対して `align-items: center`が当たっているので、その子要素である `h1` は中央に寄るため、結果的にロゴが中央に寄るようになります。

2023-07-12 04:57 UTC, IwaseMio commented
出来ました！ありがとうございます。確認お願いします。

2023-07-12 06:13 UTC, higashiji2000 approved these changes
LGTMです🐏

2023-07-12 06:21 UTC, merged