About・Coursesの作成
IwaseMio/frontend-basic-site pull request #2
Opened 2023-07-12 07:11 UTC by IwaseMio

よろしくお願いします。

2023-07-12 15:51 UTC, yuta-frontend commented
![image](https://github.com/IwaseMio/frontend-basic-site/assets/111492663/00e1987f-12bd-4ea3-84cb-6dcb9817e78e)

2023-07-12 15:54 UTC, yuta-frontend commented
headerにかぶっているのでz-indexの調整をした方がいいかもです
※レビュー通っているので後回しで大丈夫だと思います
例）headerのz-indexをz-index: 11;に変更する

2023-07-12 16:04 UTC, yuta-frontend commented
![image](https://github.com/IwaseMio/frontend-basic-site/assets/111492663/61a51072-490d-4f31-9b98-db33bd714002)
「すべてのコースを見る」の実装お願いします

2023-07-12 16:16 UTC, yuta-frontend commented
初めてのレビューで間違えてるところがあるかもしれないので、ちょっとでも疑問点があったら質問してくれると嬉しいです。

2023-07-13 00:10 UTC, IwaseMio commented
修正しました！ありがとうございます。

2023-07-13 14:32 UTC, Higashiji requested changes

2023-07-13 14:32 UTC, Higashiji commented on style.css
> +}
`h` 要素はデフォルトでブロック要素なので、こちらの記述は不要です！

2023-07-13 14:32 UTC, higashiji2000 commented on index.html
> +          <a href="." class="course-card">
```suggestion
          <a href="#" class="course-card">
```

2023-07-13 14:39 UTC, higashiji2000 approved these changes
LGTM 🇦🇷

2023-07-13 14:39 UTC, merged