Signup/Footerの作成
IwaseMio/frontend-basic-site pull request #3
Opened 2023-07-15 03:55 UTC by IwaseMio

2023-07-15 04:22 UTC, haruchu commented
pタグでデフォルトのmarginがあるので、figmaにない余白が生まれてしまっていますね🥲
<img width="806" alt="スクリーンショット 2023-07-15 13 20 53" src="https://github.com/IwaseMio/frontend-basic-site/assets/66406382/246b2478-9f7b-4798-a03f-349e5a27ea20">

2023-07-15 04:26 UTC, haruchu commented on style.css
> +  gap: 20px;
これスマホのサイズの時は5pxかな？？

2023-07-15 04:34 UTC, tomu-fujikawa commented on style.css
> +  gap: 20px;
見た目変わらないけど、gapよりrow-gapの方がいいかな

2023-07-15 04:34 UTC, haruchu commented
お手本サイトを見る感じ、pc画面では40px, スマホ画面では20px常に右に余白がある状態なので合わせてみてください！
<img width="567" alt="スクリーンショット 2023-07-15 13 32 56" src="https://github.com/IwaseMio/frontend-basic-site/assets/66406382/b2eb282a-3236-4bd0-987f-c687d34f802c">

2023-07-15 14:46 UTC, higashiji2000 requested changes
CSSが適度に共通化出来ていて素晴らしいです！！
数点コメントしてあるので、修正お願いします。

2023-07-15 14:46 UTC, higashiji2000 commented on index.html
> +          </a>
【修正不要】
`form` の送信に使えるのは `button` 要素 or `type="submit"` が設定された `input` 要素です。
「送信する」ボタンは上記のどちらかで作成するのが理想ですが、実際に生HTMLのフォームを書くことは今どきほとんど無いので、今回はそこまで厳密性を求めません！

2023-07-15 14:46 UTC, higashiji2000 commented on style.css
> +.signup-section-ttl {
【修正不要】
数名の省略は避けるべきというのが最近の風潮なので、 `ttl` → `title` としたほうが可読性は高いかもしれません。
ただ chapter2 でマージした範囲に似たようなclass名があり、そことの整合性の方を重視したいので、今回は修正不要です！

参考：https://shinkufencer.hateblo.jp/entry/2022/04/16/000000

2023-07-15 14:46 UTC, higashiji2000 commented on style.css
> +  color: var(--color-form-placeholder-gray);
![image](https://github.com/IwaseMio/frontend-basic-site/assets/83479175/4eec63eb-a239-437d-9b55-3b5973d120a7)
ユーザーが入力した文字も色が薄くなってしまっています。
pladeholderは薄く、ユーザーが入力した文字は黒く、というのが理想なので、修正をお願いします！
`::placeholder` 疑似要素を使うと実現できます。

2023-07-15 14:46 UTC, higashiji2000 commented on style.css
> +}
IDセレクタは詳細度が高いので、可能であればクラスセレクタを使ってください！
なるべく詳細度を均一に保って、上書きをしやすくするという観点がCSS設計で大切になります。

2023-07-15 14:46 UTC, higashiji2000 commented on style.css
> +}
[お手本サイト](https://shinonome.io/frontend-basic-2023-html-css-assignment-baseline/)を参考に、hover時のアニメーションの実装をお願いします。
chapter2でやったのと同じ感じです。

2023-07-15 23:21 UTC, IwaseMio commented
修正しました！

2023-07-16 16:48 UTC, higashiji2000 approved these changes
LGTMです 🎾

2023-07-18 11:54 UTC, merged